system:
  host: rivanna
  dataset_root: null

experiment:
  directive: "a100-80gb"
  profile: ["LegoGearsUltra"]
  val_frac: [0.10]
  num_gpus: [1]
  ultra_model: ["yolo11m.pt"]
  color_preset: [null]
  repeat: [1]

ee:
  identifier: "{experiment.profile}_{experiment.ultra_model}_val{experiment.val_frac}_repeat{experiment.repeat}"
